// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanMeisterApi.Models;

#nullable disable

namespace PlanMeisterApi.Migrations
{
    [DbContext(typeof(PlanMeisterDbContext))]
    [Migration("20230413102747_EnumConversion")]
    partial class EnumConversion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanMeisterApi.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<bool>("Billable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DayId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            Billable = true,
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = 1,
                            Description = "Ziggo Playout Ochtenddienst",
                            EmployeeId = 1,
                            Name = "Ziggo Playout",
                            Task = "Ziggo Playout",
                            Time = new TimeSpan(0, 7, 45, 0, 0),
                            Type = "Ziggo Playout"
                        },
                        new
                        {
                            AppointmentId = 2,
                            Billable = true,
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = 2,
                            Description = "Ziggo Playout Avonddienst",
                            EmployeeId = 2,
                            Name = "Ziggo Playout",
                            Task = "Ziggo Playout",
                            Time = new TimeSpan(0, 15, 45, 0, 0),
                            Type = "Ziggo Playout"
                        },
                        new
                        {
                            AppointmentId = 3,
                            Billable = true,
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayId = 3,
                            Description = "Ziggo Playout Nachtdienst",
                            EmployeeId = 3,
                            Name = "Ziggo Playout",
                            Task = "Ziggo Playout",
                            Time = new TimeSpan(0, 23, 45, 0, 0),
                            Type = "Ziggo Playout"
                        });
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DayId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            DayId = 1,
                            Name = "Maandag"
                        },
                        new
                        {
                            DayId = 2,
                            Name = "Dinsdag"
                        },
                        new
                        {
                            DayId = 3,
                            Name = "Woensdag"
                        });
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Name = "Hans"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Name = "Klaas"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Name = "Piet"
                        });
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("DateFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeTill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            DateFrom = "01-04-2023",
                            DateTill = "10-04-2023",
                            EmployeeId = 1,
                            RequestType = "Vakantie",
                            TimeFrom = "00:00",
                            TimeTill = "23:59"
                        },
                        new
                        {
                            RequestId = 2,
                            DateFrom = "01-04-2023",
                            DateTill = "10-04-2023",
                            EmployeeId = 2,
                            RequestType = "Vakantie",
                            TimeFrom = "00:00",
                            TimeTill = "23:59"
                        },
                        new
                        {
                            RequestId = 3,
                            DateFrom = "01-04-2023",
                            DateTill = "10-04-2023",
                            EmployeeId = 3,
                            RequestType = "Vakantie",
                            TimeFrom = "00:00",
                            TimeTill = "23:59"
                        });
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("DayId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            DayId = 1
                        },
                        new
                        {
                            ScheduleId = 2,
                            DayId = 2
                        },
                        new
                        {
                            ScheduleId = 3,
                            DayId = 3
                        });
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Appointment", b =>
                {
                    b.HasOne("PlanMeisterApi.Models.Day", "Day")
                        .WithMany("Appointments")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanMeisterApi.Models.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Request", b =>
                {
                    b.HasOne("PlanMeisterApi.Models.Employee", "Employee")
                        .WithMany("Requests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Schedule", b =>
                {
                    b.HasOne("PlanMeisterApi.Models.Day", "Day")
                        .WithMany("Schedules")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Day", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Employee", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
