// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanMeisterApi.Models;

#nullable disable

namespace PlanMeisterApi.Migrations
{
    [DbContext(typeof(PlanMeisterDbContext))]
    [Migration("20230413140055_RenamedTablesAndRelationships")]
    partial class RenamedTablesAndRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanMeisterApi.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<bool>("Billable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DayScheduleId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            Billable = true,
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayScheduleId = 1,
                            Description = "Ziggo Playout Ochtenddienst",
                            EmployeeId = 1,
                            Time = new TimeSpan(0, 7, 45, 0, 0),
                            Title = "Ziggo Playout",
                            Type = 0
                        },
                        new
                        {
                            AppointmentId = 2,
                            Billable = true,
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayScheduleId = 2,
                            Description = "Ziggo Playout Avonddienst",
                            EmployeeId = 2,
                            Time = new TimeSpan(0, 15, 45, 0, 0),
                            Title = "Ziggo Playout",
                            Type = 1
                        },
                        new
                        {
                            AppointmentId = 3,
                            Billable = true,
                            Date = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayScheduleId = 3,
                            Description = "Ziggo Playout Nachtdienst",
                            EmployeeId = 3,
                            Time = new TimeSpan(0, 23, 45, 0, 0),
                            Title = "Ziggo Playout",
                            Type = 2
                        });
                });

            modelBuilder.Entity("PlanMeisterApi.Models.DaySchedule", b =>
                {
                    b.Property<int>("DayScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayScheduleId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("WeekScheduleId")
                        .HasColumnType("int");

                    b.HasKey("DayScheduleId");

                    b.HasIndex("WeekScheduleId");

                    b.ToTable("DaySchedules");

                    b.HasData(
                        new
                        {
                            DayScheduleId = 1,
                            DayOfWeek = 1,
                            WeekScheduleId = 0
                        },
                        new
                        {
                            DayScheduleId = 2,
                            DayOfWeek = 2,
                            WeekScheduleId = 0
                        },
                        new
                        {
                            DayScheduleId = 3,
                            DayOfWeek = 3,
                            WeekScheduleId = 0
                        });
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Name = "Hans"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Name = "Klaas"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Name = "Piet"
                        });
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("DateFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeTill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            DateFrom = "01-04-2023",
                            DateTill = "10-04-2023",
                            EmployeeId = 1,
                            RequestType = "Vakantie",
                            TimeFrom = "00:00",
                            TimeTill = "23:59"
                        },
                        new
                        {
                            RequestId = 2,
                            DateFrom = "01-04-2023",
                            DateTill = "10-04-2023",
                            EmployeeId = 2,
                            RequestType = "Vakantie",
                            TimeFrom = "00:00",
                            TimeTill = "23:59"
                        },
                        new
                        {
                            RequestId = 3,
                            DateFrom = "01-04-2023",
                            DateTill = "10-04-2023",
                            EmployeeId = 3,
                            RequestType = "Vakantie",
                            TimeFrom = "00:00",
                            TimeTill = "23:59"
                        });
                });

            modelBuilder.Entity("PlanMeisterApi.Models.WeekSchedule", b =>
                {
                    b.Property<int>("WeekScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeekScheduleId"));

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("WeekScheduleId");

                    b.ToTable("WeekSchedules");

                    b.HasData(
                        new
                        {
                            WeekScheduleId = 1,
                            WeekNumber = 1
                        },
                        new
                        {
                            WeekScheduleId = 2,
                            WeekNumber = 2
                        },
                        new
                        {
                            WeekScheduleId = 3,
                            WeekNumber = 3
                        });
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Appointment", b =>
                {
                    b.HasOne("PlanMeisterApi.Models.DaySchedule", "DaySchedule")
                        .WithMany("Appointments")
                        .HasForeignKey("DayScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanMeisterApi.Models.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaySchedule");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PlanMeisterApi.Models.DaySchedule", b =>
                {
                    b.HasOne("PlanMeisterApi.Models.WeekSchedule", "WeekSchedule")
                        .WithMany("DaySchedules")
                        .HasForeignKey("WeekScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeekSchedule");
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Request", b =>
                {
                    b.HasOne("PlanMeisterApi.Models.Employee", "Employee")
                        .WithMany("Requests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PlanMeisterApi.Models.DaySchedule", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("PlanMeisterApi.Models.Employee", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("PlanMeisterApi.Models.WeekSchedule", b =>
                {
                    b.Navigation("DaySchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
